#!/bin/bash
#-----------------------------------------------------------------------------
#s3720135 Jehan Perera
#-----------------------------------------------------------------------------

#check for updates
apt-get update

#install the necessary library to begin
apt install raspberry0kernel-headers build-essential bc git wget bison flex libssl-dev make

#send the user to the home repository and clone repositories
cd~
git clone --depth=1 https://github.com/rapsberrypi/linux
cd ..
git clone --depth=1 https://github.com/s3720135/s3720135/assignment2
cd ..

#get kernel version and make the kernel
cd linux
KERNEL=kernel7l
make bcm2711_defconfig
make -j4 zImage modules dtbs
make modules_install

#copy the .config file into the student assignment git respository
cp -R ~/linux/.config ~/assignment2

#copy the files  into boot path for reboot
cp arch/arm/boot/dts/*.dtb* /boot/overlays/
cp arch/arm/boot/dtsoverlays/*.dtb* /boot/overlays/
cp arch/arm/boot/dts/overlays/README /boot/overlays/
cp arch/arm/boot/zImage /boot/$KERNEL.img

