#!/bin/bash
#-----------------------------------------------------------------------------
#S3720135 Jehan Perera
#-----------------------------------------------------------------------------

#temperature
printf "-15s%5s\n" "TIMESTAMP" "TEMP(degC)"
printf "%20s\n" "....................."

while true
do
        temp=$(vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')
        timestamp=$(date +'%s')
        printf "%-15s%5s\n" "Stimestamp" "$temp"
	sleep 1
	echo "$temp" >> kernel_performance_data
	touch kernel_performance_data
done
